[project]
name = "doulingo-speak"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "edge-tts>=7.2.8",
    "fastapi>=0.141.1",
    "gtts>=2.5.4",
    "pydantic>=2.13.4",
    "python-dotenv>=1.2.2",
    "python-multipart>=0.0.32",
    "requests>=2.34.2",
    "uvicorn>=0.52.0",
]

[tool.pytest.ini_options]
pythonpath = "."
testpaths = ["tests"]

[tool.ruff]
lint.ignore = ["BLE001", "G201", "SIM103", "S110", "S112", "PLW1508", "RUF015", "RUF059", "E501", "DTZ005", "PLW1510", "TRY002", "ASYNC210", "B008", "RUF012", "PERF402"]


[tool.mypy]
ignore_missing_imports = true
explicit_package_bases = true
exclude = ["main.py"]



