from app.core.ai_engine import ai_engine
from app.scenarios import list_scenarios


def test_summarize_or_prune_history_under_threshold():
    """Verify history under 30 messages (15 exchanges) is not truncated."""
    history = [
        {"role": "user" if i % 2 == 0 else "assistant", "content": f"Message {i}"}
        for i in range(20)
    ]
    recent_items, summary_block = ai_engine._summarize_or_prune_history(history, max_exchanges=15)
    assert len(recent_items) == 20
    assert summary_block == ""

def test_summarize_or_prune_history_over_threshold():
    """Verify history over 30 messages (15 exchanges) triggers truncation & summarization guard."""
    history = [
        {"role": "user" if i % 2 == 0 else "assistant", "content": f"Message {i}"}
        for i in range(34)
    ]
    recent_items, summary_block = ai_engine._summarize_or_prune_history(history, max_exchanges=15)
    assert len(recent_items) == 10
    assert "[MULTI-TURN CONTEXT SUMMARY" in summary_block
    assert "PRUNED 24 PREVIOUS MESSAGES (12 TURNS)" in summary_block

def test_build_token_efficient_prompt_with_truncation():
    """Verify _build_token_efficient_prompt incorporates context summary when history > 15 exchanges."""
    scenarios = list_scenarios()
    scenario = scenarios[0] if scenarios else {"title": "Coffee Shop", "description": "Ordering coffee", "open_story_guide": "Guide"}
    character = {"name": "Duo", "trait": "Friendly", "speech_style": "Casual", "country": "USA", "role": "Barista"}

    history = [
        {"role": "user" if i % 2 == 0 else "assistant", "content": f"Dialogue turn content {i}"}
        for i in range(36)
    ]
    prompt = ai_engine._build_token_efficient_prompt(
        scenario=scenario,
        character=character,
        user_transcript="I would like a cappuccino please.",
        history=history,
        turn_count=19,
        level=1
    )
    assert "[MULTI-TURN CONTEXT SUMMARY" in prompt
    assert "Dialogue turn content 35" in prompt

def test_ai_engine_material_bank_topic_fallback():
    """Verify ai_engine falls back to MaterialBank when scenario_id is not in static scenarios dict."""
    character = {"name": "Lily", "trait": "Encouraging", "speech_style": "Friendly", "country": "UK", "role": "Teacher"}
    prompt = ai_engine._build_token_efficient_prompt(
        scenario={"id": "topic_001_education", "title": "Education & Learning", "description": "Discussing education"},
        character=character,
        user_transcript="I think online learning is flexible.",
        history=[],
        turn_count=1,
        level=5
    )
    assert "CONVERSATION TOPIC" in prompt
    assert "Education & Learning" in prompt or "topic_001_education" in prompt

def test_ai_engine_prompt_factory_integration():
    """Verify prompt generated by ai_engine integrates sampled MaterialBank components."""
    scenario = {"id": "coffee_shop", "title": "Coffee Shop", "description": "Ordering coffee"}
    character = {"id": "lily", "name": "Lily", "trait": "Helpful", "speech_style": "Polite", "role": "Barista"}
    
    prompt = ai_engine._build_token_efficient_prompt(
        scenario=scenario,
        character=character,
        user_transcript="Can I get an espresso?",
        history=[],
        turn_count=1,
        level=8
    )
    assert "CONVERSATION TOPIC" in prompt
    assert "Lily" in prompt


def test_ai_engine_rag_integration():
    """Verify _build_token_efficient_prompt includes REFERENCE DIALOGUES FROM BOOKS."""
    scenario = {"id": "det_childhood_memory", "title": "Childhood Memories"}
    character = {"id": "lily", "name": "Lily", "trait": "Helpful", "speech_style": "Polite", "role": "Friend"}

    prompt = ai_engine._build_token_efficient_prompt(
        scenario=scenario,
        character=character,
        user_transcript="I remember playing in the park.",
        history=[],
        turn_count=1,
        level=9
    )
    assert "REFERENCE DIALOGUES FROM BOOKS" in prompt


def test_parse_json_response_structured_cot():
    """Verify _parse_json_response extracts Structured CoT fields (natural_draft, vocab_check, final_response)."""
    json_text = """
    {
      "natural_draft": "I am thinking about asking about coffee preferences.",
      "vocab_check": "All words are basic A1 level suitable for beginner.",
      "final_response": "I like hot coffee in the morning. Do you like coffee?",
      "user_feedback": {
        "grammar_status": "Clean & Clear",
        "corrected_text": "I like coffee too.",
        "native_phrasing": "I like coffee as well.",
        "duo_reaction": "happy"
      }
    }
    """
    res = ai_engine._parse_json_response(json_text)
    assert res["natural_draft"] == "I am thinking about asking about coffee preferences."
    assert res["vocab_check"] == "All words are basic A1 level suitable for beginner."
    assert res["final_response"] == "I like hot coffee in the morning. Do you like coffee?"
    assert res["ai_response"] == "I like hot coffee in the morning. Do you like coffee?"
    assert res["user_feedback"]["grammar_status"] == "Clean & Clear"


def test_heuristic_validation_loop_pass(monkeypatch):
    """Verify Heuristic Validation Loop returns immediately in 1 call when vocabulary ceiling check passes."""
    mock_res = {
        "natural_draft": "Drafting simple response about pets",
        "vocab_check": "Checked level ceiling A1",
        "final_response": "I have a cat. Do you like cat?",
        "ai_response": "I have a cat. Do you like cat?",
        "user_feedback": {"grammar_status": "Clean & Clear"}
    }
    monkeypatch.setattr(ai_engine, "_call_llm_providers", lambda prompt, temp=0.8: mock_res)

    res = ai_engine._call_llm_with_heuristic_loop("Test prompt", level=2)
    assert res is not None
    assert res["final_response"] == "I have a cat. Do you like cat?"
    assert res["heuristic_check"]["passed"] is True
    assert res["heuristic_check"]["retries"] == 0


def test_heuristic_validation_loop_retry_on_violation(monkeypatch):
    """Verify Heuristic Validation Loop triggers retry feedback when initial response contains high-level vocabulary."""
    calls = []
    
    # First call returns violating words for Level 2 / A1 (e.g. "complex", "deeply")
    violating_res = {
        "natural_draft": "High level draft",
        "vocab_check": "Not checked properly",
        "final_response": "I contemplate complex philosophical topics deeply every single day.",
        "ai_response": "I contemplate complex philosophical topics deeply every single day.",
        "user_feedback": {"grammar_status": "Clean & Clear"}
    }
    # Second call (retry) returns downgraded A1 words
    downgraded_res = {
        "natural_draft": "Downgraded draft with simple words",
        "vocab_check": "Verified basic A1 words used",
        "final_response": "I think about big ideas. What do you think?",
        "ai_response": "I think about big ideas. What do you think?",
        "user_feedback": {"grammar_status": "Clean & Clear"}
    }

    def mock_providers(prompt, temp=0.8):
        calls.append(prompt)
        if len(calls) == 1:
            return violating_res
        return downgraded_res

    monkeypatch.setattr(ai_engine, "_call_llm_providers", mock_providers)

    res = ai_engine._call_llm_with_heuristic_loop("Test prompt", level=2, max_retries=2)
    assert res is not None
    assert len(calls) == 2
    assert res["heuristic_check"]["retries"] == 1
    assert "CRITICAL HEURISTIC VALIDATION FAILURE" in calls[1]
    assert "complex" in calls[1] or "deeply" in calls[1]
    assert res["final_response"] == "I think about big ideas. What do you think?"


def test_process_turn_structured_cot(monkeypatch):
    """Verify process_turn returns Structured Output CoT fields."""
    mock_res = {
        "natural_draft": "Draft about tea",
        "vocab_check": "Verified basic words",
        "final_response": "I like green tea. Do you like tea?",
        "ai_response": "I like green tea. Do you like tea?",
        "user_feedback": {"grammar_status": "Clean & Clear"}
    }
    monkeypatch.setattr(ai_engine, "_call_llm_providers", lambda prompt, temp=0.8: mock_res)

    res = ai_engine.process_turn(
        scenario_id="coffee_shop",
        character_id="lily",
        user_transcript="I want tea.",
        conversation_history=[],
        level=2
    )
    assert "natural_draft" in res
    assert "vocab_check" in res
    assert "final_response" in res
    assert "ai_response" in res



