from app.ai_engine import ai_engine
from app.scenarios import list_scenarios

def test_summarize_or_prune_history_under_threshold():
    """Verify history under 30 messages (15 exchanges) is not truncated."""
    history = [
        {"role": "user" if i % 2 == 0 else "assistant", "content": f"Message {i}"}
        for i in range(20)
    ]
    recent_items, summary_block = ai_engine._summarize_or_prune_history(history, max_exchanges=15)
    assert len(recent_items) == 20
    assert summary_block == ""

def test_summarize_or_prune_history_over_threshold():
    """Verify history over 30 messages (15 exchanges) triggers truncation & summarization guard."""
    history = [
        {"role": "user" if i % 2 == 0 else "assistant", "content": f"Message {i}"}
        for i in range(34)
    ]
    recent_items, summary_block = ai_engine._summarize_or_prune_history(history, max_exchanges=15)
    assert len(recent_items) == 10
    assert "[MULTI-TURN CONTEXT SUMMARY" in summary_block
    assert "PRUNED 24 PREVIOUS MESSAGES (12 TURNS)" in summary_block

def test_build_token_efficient_prompt_with_truncation():
    """Verify _build_token_efficient_prompt incorporates context summary when history > 15 exchanges."""
    scenarios = list_scenarios()
    scenario = scenarios[0] if scenarios else {"title": "Coffee Shop", "description": "Ordering coffee", "open_story_guide": "Guide"}
    character = {"name": "Duo", "trait": "Friendly", "speech_style": "Casual", "country": "USA", "role": "Barista"}

    history = [
        {"role": "user" if i % 2 == 0 else "assistant", "content": f"Dialogue turn content {i}"}
        for i in range(36)
    ]
    prompt = ai_engine._build_token_efficient_prompt(
        scenario=scenario,
        character=character,
        user_transcript="I would like a cappuccino please.",
        history=history,
        turn_count=19,
        level=1
    )
    assert "[MULTI-TURN CONTEXT SUMMARY" in prompt
    assert "Dialogue turn content 35" in prompt

def test_ai_engine_material_bank_topic_fallback():
    """Verify ai_engine falls back to MaterialBank when scenario_id is not in static scenarios dict."""
    character = {"name": "Lily", "trait": "Encouraging", "speech_style": "Friendly", "country": "UK", "role": "Teacher"}
    prompt = ai_engine._build_token_efficient_prompt(
        scenario={"id": "topic_001_education", "title": "Education & Learning", "description": "Discussing education"},
        character=character,
        user_transcript="I think online learning is flexible.",
        history=[],
        turn_count=1,
        level=5
    )
    assert "CONVERSATION TOPIC" in prompt
    assert "Education & Learning" in prompt or "topic_001_education" in prompt

def test_ai_engine_prompt_factory_integration():
    """Verify prompt generated by ai_engine integrates sampled MaterialBank components."""
    scenario = {"id": "coffee_shop", "title": "Coffee Shop", "description": "Ordering coffee"}
    character = {"id": "lily", "name": "Lily", "trait": "Helpful", "speech_style": "Polite", "role": "Barista"}
    
    prompt = ai_engine._build_token_efficient_prompt(
        scenario=scenario,
        character=character,
        user_transcript="Can I get an espresso?",
        history=[],
        turn_count=1,
        level=8
    )
    assert "CONVERSATION TOPIC" in prompt
    assert "Lily" in prompt

