"""
Main FastAPI App for Duolingo Speak
Features:
- LLM-quality Natural Vietnamese Translations (via ai_engine, NO Google Translate scraping).
- Mobile PWA Speech Recognition Fix (Full transcript capture).
- Saved Vocabulary Book Endpoint (/api/saved_words).
- Permanent SQLite Word Dictionary Storage & RAM Cache (0ms Instant Word Lookup).
- Expressive Neural Voice TTS (/api/tts).
- Granular 20-Level Difficulty System with per-level hard constraints.
"""

from fastapi import FastAPI, HTTPException, Query, UploadFile, File, Form
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse, StreamingResponse
from pydantic import BaseModel
from typing import List, Dict, Any, Optional
import os
import uuid
import unicodedata
import requests
from urllib.parse import quote

from app.scenarios import list_scenarios, get_scenario
from app.characters import list_characters, get_character
from app.db import add_custom_scenario, get_translated_word, save_translated_word, get_all_saved_words
from app.ai_engine import ai_engine
from app.tts_service import generate_tts_mp3

app = FastAPI(title="Duolingo Speak - Unlimited AI Roleplays")

# Global In-Memory Caches for Instant 0ms Word Lookup
TRANSLATION_CACHE: Dict[str, str] = {}
IPA_CACHE: Dict[str, str] = {}

class TurnRequest(BaseModel):
    scenario_id: str
    character_id: Optional[str] = None
    user_transcript: str
    conversation_history: List[Dict[str, str]] = []
    level: Optional[int] = 1

class StartScenarioRequest(BaseModel):
    scenario_id: str
    character_id: Optional[str] = None
    level: Optional[int] = 1

class CustomScenarioRequest(BaseModel):
    title: str
    category: Optional[str] = "Everyday Life ☕"
    icon: Optional[str] = "💬"
    color: Optional[str] = "#1CB0F6"
    level: Optional[str] = "Beginner"
    level_code: Optional[str] = "A2"
    default_character: Optional[str] = "rajesh"
    description: Optional[str] = "Custom everyday life topic"
    objective: Optional[str] = "Express your thoughts freely."
    suggested_vocabulary: Optional[List[str]] = ["Everyday conversation", "Free chat"]
    mode: Optional[str] = "roleplay"

class SentenceTranslateRequest(BaseModel):
    text: str
    target_lang: Optional[str] = "vi"
    character_name: Optional[str] = ""
    scenario_title: Optional[str] = ""
    context_history: Optional[List[str]] = []

class DetSpeechEvalRequest(BaseModel):
    scenario_id: str
    user_speech: str
    duration_seconds: Optional[int] = 120
    mode: Optional[str] = "read_then_speak"
    wpm: Optional[int] = None
    pause_count: Optional[int] = None
    filler_count: Optional[int] = None

# NOTE: Google Translate gtx scraping (client=gtx) has been REMOVED.
# Translation fallback is now handled inside ai_engine._fallback_llm_translate()
# which uses Groq/Gemini LLM for high-quality natural Vietnamese output.

@app.get("/api/scenarios")
def api_list_scenarios():
    return {"scenarios": list_scenarios()}

@app.get("/api/scenarios/{scenario_id}")
def api_get_scenario(scenario_id: str):
    scenario = get_scenario(scenario_id)
    if not scenario:
        raise HTTPException(status_code=404, detail="Scenario not found")
    return scenario

@app.post("/api/custom_scenarios")
def api_create_custom_scenario(payload: CustomScenarioRequest):
    if not payload.title.strip():
        raise HTTPException(status_code=400, detail="Title cannot be empty")
    prefix = "det_custom_" if payload.mode == "ielts_exam" else "custom_"
    sc_id = f"{prefix}{uuid.uuid4().hex[:8]}"
    sc_data = {
        "id": sc_id,
        "title": payload.title,
        "category": payload.category,
        "icon": payload.icon or "💬",
        "color": payload.color or "#1CB0F6",
        "level": payload.level or "Beginner",
        "level_code": payload.level_code or "A2",
        "default_character": payload.default_character or "rajesh",
        "description": payload.description or "Everyday life topic",
        "objective": payload.objective or "Express thoughts freely.",
        "suggested_vocabulary": payload.suggested_vocabulary or ["Everyday chat"],
        "mode": payload.mode or "roleplay"
    }
    saved = add_custom_scenario(sc_data)
    return {"status": "success", "scenario": saved}

@app.get("/api/characters")
def api_list_characters():
    return {"characters": list_characters()}

@app.get("/api/characters/{character_id}")
def api_get_character(character_id: str):
    character = get_character(character_id)
    if not character:
        raise HTTPException(status_code=404, detail="Character not found")
    return character

@app.post("/api/start_scenario")
def api_start_scenario(payload: StartScenarioRequest):
    try:
        greeting = ai_engine.start_roleplay_greeting(
            scenario_id=payload.scenario_id,
            character_id=payload.character_id,
            level=payload.level or 1
        )
        # ai_response_vi is generated by AI in the same call.
        # If missing, frontend will fetch on-demand via /api/translate_sentence when user clicks Translate.
        return greeting
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/api/process_turn")
def api_process_turn(payload: TurnRequest):
    if not payload.user_transcript.strip():
        raise HTTPException(status_code=400, detail="User transcript cannot be empty")
    try:
        result = ai_engine.process_turn(
            scenario_id=payload.scenario_id,
            character_id=payload.character_id,
            user_transcript=payload.user_transcript,
            conversation_history=payload.conversation_history,
            level=payload.level or 1
        )
        return result
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/api/transcribe_audio")
async def api_transcribe_audio(
    file: Optional[UploadFile] = File(None),
    fallback_text: str = Form("")
):
    """
    Transcribes recorded microphone audio using Groq Whisper / Gemini Audio ASR.
    Falls back to browser Web Speech API text if audio is empty or API unavailable.
    """
    audio_bytes = b""
    filename = "speech.webm"
    if file:
        audio_bytes = await file.read()
        filename = file.filename or "speech.webm"

    if not audio_bytes and not fallback_text.strip():
        raise HTTPException(status_code=400, detail="No audio or fallback text provided")

    result = await ai_engine.transcribe_audio(audio_bytes, filename=filename, fallback_text=fallback_text)
    return result

# In-Memory cache for on-demand sentence translations
SENTENCE_TRANSLATION_CACHE: Dict[str, str] = {}

@app.post("/api/translate_sentence")
def api_translate_sentence(payload: SentenceTranslateRequest):
    """
    On-demand sentence translation endpoint.
    Called LAZILY only when user explicitly clicks the Translate button.
    Caches results in RAM — same sentence translated only ONCE per session.
    Uses the same LLM pool as the main AI engine (Groq → Gemini fallback).
    ZERO extra API calls unless user actively requests translation.
    """
    text = payload.text.strip()
    if not text:
        raise HTTPException(status_code=400, detail="Text cannot be empty")

    target_lang = payload.target_lang or "vi"
    cache_key = f"{target_lang}::{text}"

    # Check RAM cache first — avoids repeat LLM calls for same sentence
    if cache_key in SENTENCE_TRANSLATION_CACHE:
        return {"translation": SENTENCE_TRANSLATION_CACHE[cache_key], "cached": True}

    translation = ai_engine._professional_vietnamese_localization(
        text,
        character_name=payload.character_name or "",
        scenario_title=payload.scenario_title or "",
        context_history=payload.context_history or []
    )
    if not translation:
        translation = ai_engine._fallback_llm_translate(text)
    if not translation:
        translation = text  # Show original if all LLMs fail

    SENTENCE_TRANSLATION_CACHE[cache_key] = translation
    return {"translation": translation, "cached": False}

@app.post("/api/det/evaluate_speech")
async def api_det_evaluate_speech(payload: DetSpeechEvalRequest):
    """
    Evaluates DET Speaking tasks (Read, Then Speak & Interactive Speaking).
    Returns official 10-160 DET score, CEFR band, examiner critique, C1/C2 upgrades, and band-160 sample speech.
    """
    scenario = get_scenario(payload.scenario_id)
    if not scenario:
        raise HTTPException(status_code=404, detail="DET Scenario not found")
    
    result = await ai_engine.evaluate_det_speech(
        scenario=scenario,
        user_speech=payload.user_speech.strip(),
        duration_seconds=payload.duration_seconds or 120,
        mode=payload.mode or "read_then_speak",
        wpm=payload.wpm,
        pause_count=payload.pause_count,
        filler_count=payload.filler_count
    )
    return result

@app.get("/api/saved_words")
def api_get_saved_words(target_lang: Optional[str] = Query(None, description="Optional target language filter")):
    words = get_all_saved_words(target_lang)
    return {"count": len(words), "words": words}

@app.get("/api/translate_word")
def api_translate_word(
    word: str = Query(..., description="Word to look up"),
    target_lang: str = Query("vi", description="Target translation language code (vi, en-def, es, fr)")
):
    """
    High-Quality Natural Dictionary Lookup Endpoint.
    Uses dt=bd parameter to fetch natural, accurate dictionary meanings.
    """
    clean_word = word.strip().strip(".,!?;:\"'()[]{}")
    if not clean_word:
        raise HTTPException(status_code=400, detail="Word cannot be empty")

    cache_key = f"{clean_word.lower()}_{target_lang}"
    lang_labels = {
        "vi": "Tiếng Việt",
        "en-def": "English Definition",
        "es": "Spanish",
        "fr": "French"
    }

    # 1. Check RAM Cache (0ms response)
    if cache_key in TRANSLATION_CACHE:
        return {
            "word": clean_word,
            "target_lang": target_lang,
            "target_label": lang_labels.get(target_lang, "Translation"),
            "translation": TRANSLATION_CACHE[cache_key],
            "phonetic": IPA_CACHE.get(clean_word.lower(), f"/{clean_word.lower()}/")
        }

    # 2. Check Permanent SQLite Database
    db_word = get_translated_word(clean_word, target_lang)
    if db_word:
        TRANSLATION_CACHE[cache_key] = db_word["translation"]
        IPA_CACHE[clean_word.lower()] = db_word["phonetic"]
        return db_word

    # 3. High-Quality Dictionary API Lookup (dt=t & dt=bd for natural everyday terms)
    tl_code = target_lang if target_lang != "en-def" else "en"
    real_translation = f"Definition of '{clean_word}'"
    try:
        gt_url = f"https://translate.googleapis.com/translate_a/single?client=gtx&sl=en&tl={tl_code}&dt=t&dt=bd&q={quote(clean_word)}"
        gt_res = requests.get(gt_url, timeout=4)
        if gt_res.status_code == 200:
            gt_data = gt_res.json()
            terms = []
            
            # Extract rich dictionary meanings if available (dt=bd)
            if len(gt_data) > 1 and gt_data[1]:
                for dict_entry in gt_data[1]:
                    if len(dict_entry) > 1 and dict_entry[1]:
                        terms.extend(dict_entry[1][:3])
            
            # Fallback to main translation
            if not terms and gt_data[0] and gt_data[0][0]:
                terms.append(gt_data[0][0][0])
                
            if terms:
                unique_terms = list(dict.fromkeys(terms))[:3]
                raw_str = ", ".join(unique_terms)
                real_translation = unicodedata.normalize('NFC', raw_str).capitalize()
    except Exception as e:
        print(f"[Translate Word] Google Translate error: {e}")

    # Fetch Real IPA Phonetics
    real_ipa = f"/{clean_word.lower()}/"
    try:
        dict_url = f"https://api.dictionaryapi.dev/api/v2/entries/en/{quote(clean_word.lower())}"
        dict_res = requests.get(dict_url, timeout=3)
        if dict_res.status_code == 200:
            dict_data = dict_res.json()
            if isinstance(dict_data, list) and dict_data[0].get("phonetics"):
                for p in dict_data[0]["phonetics"]:
                    if p.get("text"):
                        real_ipa = p["text"]
                        break
    except Exception as e:
        print(f"[Translate Word] Dictionary API error: {e}")

    # Save permanently into SQLite DB & RAM Cache
    save_translated_word(
        word=clean_word,
        target_lang=target_lang,
        target_label=lang_labels.get(target_lang, "Translation"),
        translation=real_translation,
        phonetic=real_ipa
    )
    TRANSLATION_CACHE[cache_key] = real_translation
    IPA_CACHE[clean_word.lower()] = real_ipa

    return {
        "word": clean_word,
        "target_lang": target_lang,
        "target_label": lang_labels.get(target_lang, "Translation"),
        "translation": real_translation,
        "phonetic": real_ipa
    }

@app.get("/api/tts")
def api_tts(
    text: str = Query(..., description="Text to synthesize"),
    char_id: str = Query("rajesh", description="Character ID for Neural Voice profile"),
    tld: str = Query("com", description="Top level domain fallback for accent")
):
    try:
        mp3_stream = generate_tts_mp3(text=text, char_id=char_id, tld=tld)
        return StreamingResponse(mp3_stream, media_type="audio/mpeg")
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"TTS Generation failed: {e}")

# Static files
static_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "static")
if os.path.exists(static_dir):
    app.mount("/static", StaticFiles(directory=static_dir), name="static")

@app.get("/")
def read_root():
    index_file = os.path.join(static_dir, "index.html")
    if os.path.exists(index_file):
        return FileResponse(index_file)
    return {"message": "Duolingo Speak API Server Running"}

if __name__ == "__main__":
    import uvicorn
    port = int(os.getenv("PORT", 8000))
    uvicorn.run("app.main:app", host="0.0.0.0", port=port)
