"""
Granular 20-Level Difficulty System Configurations & CEFR Rules for Duolingo Speak
"""

# Dynamic Scenario Angle Presets for Endless Variety
SCENARIO_ANGLES = [
    "Focus on budget travel, hidden local spots, and street food recommendations.",
    "Focus on flight bookings, luggage packing essentials, and airport navigation.",
    "Focus on outdoor adventures, beach activities, and scenic nature spots.",
    "Focus on hotel reservations, room upgrades, and local transportation tips.",
    "Focus on cultural festivals, evening entertainment, and meeting friendly locals.",
    "Focus on coffee tasting, cozy neighborhood cafes, and relaxing afternoon vibes.",
    "Focus on shopping deals, market bargaining, and finding unique souvenirs."
]

LEVEL_CONFIGS = {
    1: {
        "cefr": "A1",
        "sentence_words": "7-13",
        "min_words": 18,
        "max_words": 35,
        "vocab_tier": "Clear, friendly A1 everyday vocabulary (friends, food, music, movies, like, enjoy, hobbies, weekend, daily life).",
        "grammar_allowed": "Simple present tense, basic everyday phrasing. Warm, natural conversational spoken English.",
        "response_style": "2 short, natural sentences. Share a friendly thought and ask a simple open question (18-35 words).",
        "example_response": "I really enjoy hanging out with my close friends on the weekend. We usually watch movies and have fun together. What do you like to do with your best friend?",
    },
    2: {
        "cefr": "A1",
        "sentence_words": "8-14",
        "min_words": 22,
        "max_words": 40,
        "vocab_tier": "A1 everyday vocabulary. Common nouns (food, home, park, weekend, hobbies) and simple adjectives (nice, great, fun, cozy).",
        "grammar_allowed": "Simple present tense, basic past. Natural spoken phrasing.",
        "response_style": "2-3 short, natural sentences. Include everyday details and ask a friendly follow-up question (22-40 words).",
        "example_response": "I often have lunch with my close friends near the park. The food there is really good and the place is so relaxing. Where do you usually go when you hang out with friends?",
    },
    3: {
        "cefr": "A1+",
        "sentence_words": "8-15",
        "min_words": 25,
        "max_words": 45,
        "vocab_tier": "A1-A2 basic vocabulary. Common adjectives (fun, relaxing, interesting, busy) and conversational verbs.",
        "grammar_allowed": "Present simple, can/can't, basic time expressions. Natural conversational flow.",
        "response_style": "2-3 sentences with natural flow. Share an experience and ask an open-ended question (25-45 words).",
        "example_response": "Having good friends makes life so much more fun and relaxing. Whenever we meet up, we always talk about our favorite music and games. What topics do you and your friends talk about most?",
    },
    4: {
        "cefr": "A2-",
        "sentence_words": "9-15",
        "min_words": 30,
        "max_words": 55,
        "vocab_tier": "A1-A2 vocabulary. Common phrases (would like, enjoy doing, spend time with).",
        "grammar_allowed": "Present simple + 'would like' + past simple. Natural spoken English.",
        "response_style": "2-3 sentences. Express a basic preference or story clearly, then invite their thoughts (30-55 words).",
        "example_response": "My friends and I love exploring new cafes around town on Sunday afternoons. Last weekend we found a really cozy spot with great coffee. Do you have a favorite place you like to visit with your friends?",
    },
    5: {
        "cefr": "A2",
        "sentence_words": "10-16",
        "min_words": 35,
        "max_words": 70,
        "vocab_tier": "A2 everyday vocabulary. Common adjectives, basic adverbs (very, really, often, sometimes).",
        "grammar_allowed": "Present simple + past simple (regular verbs only). 'How much/many', basic questions.",
        "response_style": "2-3 sentences. Share an interesting observation and invite their thoughts (35-70 words).",
        "example_response": "I really enjoy spending time with friends on weekends. Last Saturday, we went to a small café near the park. How often do you usually meet up with your friends?",
    },
    6: {
        "cefr": "A2",
        "sentence_words": "10-16",
        "min_words": 45,
        "max_words": 85,
        "vocab_tier": "A2 vocabulary. Can use common collocations (have a meal, take a break, make a call).",
        "grammar_allowed": "Past simple (regular + irregular). Future with 'going to'. Questions with 'When, Where, Who'.",
        "response_style": "2-3 sentences. Connect past experiences or future plans with the topic (45-85 words).",
        "example_response": "I'm going to have lunch with my colleague today at the new place downtown. Last week we tried a noodle shop and it was pretty good - decent food and a really relaxed atmosphere. Have you made any plans for eating out this week?",
    },
    7: {
        "cefr": "A2+",
        "sentence_words": "10-17",
        "min_words": 45,
        "max_words": 85,
        "vocab_tier": "A2-B1 vocabulary. Basic phrasal verbs (look for, pick up, find out). Simple idioms avoided.",
        "grammar_allowed": "Past simple + continuous. Future with 'will'. Comparative adjectives (bigger, better, more).",
        "response_style": "3 sentences with smooth transitions. Ask a question that encourages elaboration (45-85 words).",
        "example_response": "I was looking for a good travel destination last week and found this amazing coastal town. The reviews were much better than the places I checked before, and the prices were more affordable too. Have you been travelling anywhere interesting recently, or are you still figuring out where to go?",
    },
    8: {
        "cefr": "B1-",
        "sentence_words": "11-17",
        "min_words": 45,
        "max_words": 85,
        "vocab_tier": "B1 vocabulary. Common idioms (a piece of cake, hit the road). Basic phrasal verbs freely.",
        "grammar_allowed": "Present perfect (have been, have done). Comparatives + superlatives. 'I think', 'I believe'.",
        "response_style": "3 sentences. Share an opinion with a reason, then ask for their viewpoint (45-85 words).",
        "example_response": "I think learning a new language is a piece of cake when you're surrounded by native speakers - immersion is by far the most effective approach I've tried. I've been studying Spanish for six months and I've already noticed a huge improvement in how confident I feel. What do you believe is the biggest obstacle to becoming fluent in another language?",
    },
    9: {
        "cefr": "B1",
        "sentence_words": "11-18",
        "min_words": 45,
        "max_words": 85,
        "vocab_tier": "B1 vocabulary. B1 idioms (on second thought, to be honest, as far as I know).",
        "grammar_allowed": "Past perfect. Conditionals (if...will). 'Used to'. Clause linking (because, although, while).",
        "response_style": "3 sentences. Use natural idiomatic expressions and conditional phrasing (45-85 words).",
        "example_response": "To be honest, I used to think social media was just a distraction, but on second thought it's actually helped me stay connected with people who matter. If I hadn't downloaded that app last year, I would have lost touch with a lot of old friends. How has technology changed the way you maintain your friendships, if at all?",
    },
    10: {
        "cefr": "B1",
        "sentence_words": "12-18",
        "min_words": 45,
        "max_words": 85,
        "vocab_tier": "B1-B2 vocabulary. Phrasal verbs freely. Common idioms used naturally in context.",
        "grammar_allowed": "Reported speech. Relative clauses (who, which, that). Second conditional (if...would).",
        "response_style": "3 sentences. Compare alternatives and present a thoughtful perspective (45-85 words).",
        "example_response": "There's this interesting debate about whether remote work, which has become the norm for so many people, actually improves productivity or quietly erodes teamwork. My colleague who switched to fully remote last year told me she gets more done, but she misses the spontaneous conversations that used to spark her best ideas. If you could design your ideal work setup, would you go fully remote, fully in-office, or something in between?",
    },
    11: {
        "cefr": "B1+",
        "sentence_words": "12-19",
        "min_words": 55,
        "max_words": 105,
        "vocab_tier": "B2 vocabulary. Abstract nouns. B2 collocations (raise awareness, make an impression).",
        "grammar_allowed": "All conditionals. Passive voice. Modals for deduction (must be, might have).",
        "response_style": "3-4 sentences. Provide structured conversational analysis with discourse markers (55-105 words).",
        "example_response": "While the immediate appeal of living in a bustling metropolis is undeniable, the hidden costs often accumulate faster than most newcomers anticipate. The convenience of round-the-clock amenities must be weighed against the constant sensory overload and the subtle toll it takes on your daily well-being. Having observed how people adapt over time, I'm inclined to think that finding a quiet sanctuary within the city is essential for long-term balance. What factors do you prioritize most when evaluating whether a neighborhood is truly livable?",
    },
    12: {
        "cefr": "B2",
        "sentence_words": "13-20",
        "min_words": 55,
        "max_words": 105,
        "vocab_tier": "B2 vocabulary. Professional, academic, and cultural expressions. Natural transitions.",
        "grammar_allowed": "Inversion for emphasis. Mixed conditionals. Complex relative and participle clauses.",
        "response_style": "3-4 sentences. Develop a compelling argument with nuanced supporting points (55-105 words).",
        "example_response": "Hardly ever do we stop to consider how profoundly architectural design influences human behavior, shaping everything from casual workplace interactions to urban stress levels. By creating spaces that intuitively encourage collaboration without sacrificing individual privacy, modern designers are fundamentally redefining what it means to work effectively. It's a fascinating paradigm shift, particularly when you look at how traditional office layouts are rapidly becoming obsolete. To what extent do you think our physical environment dictates our creative output?",
    },
    13: {
        "cefr": "B2",
        "sentence_words": "13-21",
        "min_words": 55,
        "max_words": 105,
        "vocab_tier": "B2-C1 vocabulary. Nuanced idioms (at the expense of, strike a chord, come to grips with).",
        "grammar_allowed": "Subjunctive mood. Fronted adverbials. Advanced participle clauses.",
        "response_style": "3-4 sentences. Offer deep, multi-perspective reflections with vivid examples (55-105 words).",
        "example_response": "Pursuing rapid career advancement often comes at the expense of developing deep, enduring relationships, creating a paradox that many ambitious professionals eventually struggle to reconcile. Were one to examine the trajectories of those who reach executive levels, the recurring theme is rarely a lack of talent, but rather the difficulty of sustaining emotional resilience amidst relentless pressure. Having wrestled with similar trade-offs myself, I find that setting non-negotiable personal boundaries is the only viable antidote. How do you navigate the delicate balance between professional ambition and personal fulfillment?",
    },
    14: {
        "cefr": "B2+",
        "sentence_words": "14-22",
        "min_words": 55,
        "max_words": 105,
        "vocab_tier": "B2-C1 vocabulary. Precise collocations, subtle hedging (it is plausible that, arguably).",
        "grammar_allowed": "Cleft sentences (It is...that, What I find...). Complex parallel structures.",
        "response_style": "3-4 sentences. Synthesize complex ideas with analytical elegance (55-105 words).",
        "example_response": "What is particularly striking about modern consumer culture is how seamlessly branding has evolved from communicating product utility to curating personal identity and belonging. It is no longer sufficient for a company to deliver functional excellence; they must construct an entire ethos with which consumers actively wish to align their own values. This shift has arguably transformed everyday purchasing decisions into subtle declarations of social allegiance. In what ways do you find yourself drawn to brands that reflect your personal worldview?",
    },
    15: {
        "cefr": "C1",
        "sentence_words": "15-24",
        "min_words": 65,
        "max_words": 125,
        "vocab_tier": "C1 advanced vocabulary. Sophisticated discourse markers, rhetorical elegance.",
        "grammar_allowed": "Full range of English syntax. Ellipsis, complex coordination, sophisticated subordination.",
        "response_style": "4-5 sentences. Deliver an articulate, multifaceted philosophical perspective (65-125 words).",
        "example_response": "The prevailing narrative that technological automation inevitably leads to widespread displacement overlooks the historical reality that innovation consistently creates entirely new categories of human endeavor. What we are witnessing is not the obsolescence of human labor per se, but rather an acceleration in the rate at which cognitive adaptability is demanded of the workforce. Those who cultivate cross-disciplinary fluency and emotional intelligence will likely find themselves increasingly indispensable, even as routine analytical tasks are automated away. Looking ahead, which uniquely human capabilities do you believe will remain most resilient against technological encroachment?",
    },
    16: {
        "cefr": "C1",
        "sentence_words": "16-25",
        "min_words": 65,
        "max_words": 125,
        "vocab_tier": "C1 advanced academic & cultural vocabulary. Subtle irony, metaphor, nuance.",
        "grammar_allowed": "Sophisticated stylistic inversion, nominalizations, rhetorical devices.",
        "response_style": "4-5 sentences. Construct a deeply insightful analysis exploring philosophical depth (65-125 words).",
        "example_response": "There exists a profound tension between our collective desire for institutional stability and the disruptive dynamism essential for societal renewal. Institutions, by their very design, are engineered to resist volatility, yet it is precisely through periodic institutional recalibration that societies maintain their vitality and relevance. When governance structures become excessively rigid, they inadvertently invite the very crises they were established to prevent. How might modern institutions foster internal adaptability without compromising the foundational principles that grant them legitimacy?",
    },
    17: {
        "cefr": "C1+",
        "sentence_words": "17-26",
        "min_words": 65,
        "max_words": 125,
        "vocab_tier": "C1-C2 vocabulary. Rich idiomatic expressions, profound intellectual precision.",
        "grammar_allowed": "Mastery of all complex syntactic structures. Seamless flow between registers.",
        "response_style": "4-5 sentences. Engage in scholarly yet natural dialogue with eloquence (65-125 words).",
        "example_response": "The contemporary proliferation of algorithmic curation has fundamentally restructured how we encounter information, creating insular epistemic ecosystems that subtly reinforce preexisting biases while masquerading as personalized enlightenment. This phenomena raises profound questions regarding intellectual autonomy; when the parameters of our curiosity are imperceptibly demarcated by optimization algorithms, our capacity for genuine serendipity is inevitably compromised. It is an unsettling paradox wherein the illusion of infinite choice conceals an unprecedented narrowing of perspective. What mechanisms can individuals employ to actively disrupt these algorithmic echo chambers?",
    },
    18: {
        "cefr": "C2",
        "sentence_words": "18-28",
        "min_words": 75,
        "max_words": 140,
        "vocab_tier": "C2 mastery vocabulary. Erudite, precise, evocative prose with stylistic flair.",
        "grammar_allowed": "Complete syntactic freedom. Elegant rhetorical cadence, seamless register shifts.",
        "response_style": "4-5 sentences. Articulate profound philosophical and aesthetic insights (75-140 words).",
        "example_response": "To contemplate the nature of aesthetic experience is inevitably to confront the elusive boundary between subjective sensibility and universal resonance. A truly evocative piece of art does not merely elicit passive admiration; rather, it destabilizes our habitual perceptual frameworks, compelling us to reexamine assumptions we had long taken for granted. In an era increasingly dominated by ephemeral, utilitarian content, the preservation of spaces dedicated to disinterested aesthetic contemplation becomes not merely a cultural luxury, but an imperative for the preservation of human interiority. What role do you believe authentic aesthetic engagement plays in cultivating intellectual depth?",
    },
    19: {
        "cefr": "C2",
        "sentence_words": "18-30",
        "min_words": 75,
        "max_words": 140,
        "vocab_tier": "C2 near-native / native eloquence. Literary devices, philosophical depth.",
        "grammar_allowed": "Full linguistic mastery. Sophisticated parallelisms, periodic sentences, nuanced tone.",
        "response_style": "4-5 sentences. Deliver masterful discourse blending intellectual depth with warmth (75-140 words).",
        "example_response": "The persistent dichotomy often drawn between rigorous scientific rationalism and contemplative humanistic inquiry represents, upon closer inspection, a profoundly unhelpful intellectual fracture. Each domain, when pursued to its outermost frontier, inevitably reveals the indispensability of the other; empirical inquiry without ethical reflection drifts into aimless technocracy, while philosophical contemplation ungrounded in empirical reality risks sterile abstraction. The most transformative intellectual breakthroughs in human history have almost invariably emerged at the fertile confluence of these supposedly disparate traditions. How might we better cultivate an intellectual environment that honors both empirical rigor and existential inquiry?",
    },
    20: {
        "cefr": "C2+",
        "sentence_words": "20-32",
        "min_words": 75,
        "max_words": 140,
        "vocab_tier": "C2+ Native mastery. Shakespearean/erudite wit, absolute linguistic precision.",
        "grammar_allowed": "Total syntactic and stylistic mastery. Virtuosic rhetorical control.",
        "response_style": "4-5 sentences. Deliver an extraordinary, resonant reflection of supreme eloquence (75-140 words).",
        "example_response": "In surveying the broad arc of human intellectual endeavor, one is continually struck by the realization that our most enduring insights are born not from the triumphant resolution of paradoxes, but from the disciplined, unflinching willingness to inhabit them. The pursuit of wisdom demands that we resist the seductive comfort of reductive certainties, cultivating instead a refined capacity for negative capability—an embrace of ambiguity that nourishes genuine curiosity rather than foreclosing it. It is within this liminal space between knowing and unknowing that the human spirit achieves its most luminous expressions of creativity and self-transcendence. How do you personally cultivate the discipline to remain open to uncertainty in an age that incessantly demands definitive pronouncements?",
    }
}
